name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_OUTPUT: json
      run: |
        terraform plan \
        -var="aws_region=us-east-1" \
        -var="vpc_cidr_block=10.0.0.0/16" \
        -var='public_subnet_cidrs=["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]' \
        -var='private_subnet_cidrs=["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]' \
        -var='availability_zones=["us-east-1a", "us-east-1b", "us-east-1c"]' \
        -var="env=dev" \
        -var='security_group_name=["sg-00246283c32b08144"]' \
        -var="instance_type=t2.micro" \
        -var="ami_id=ami-055b20a0020459df7"
        -var="aws_access_key=${AWS_ACCESS_KEY_ID}" \
        -var="aws_secret_key=${AWS_SECRET_ACCESS_KEY}"



    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_OUTPUT: json
      run: |
        terraform apply -auto-approve \
          -var="aws_access_key=${AWS_ACCESS_KEY_ID}" \
          -var="aws_secret_key=${AWS_SECRET_ACCESS_KEY}"
          -var="aws_region=us-east-1" \
          -var="vpc_cidr_block=10.0.0.0/16" \
          -var='public_subnet_cidrs=["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]' \
          -var='private_subnet_cidrs=["10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]' \
          -var='availability_zones=["us-east-1a", "us-east-1b", "us-east-1c"]' \
          -var="env=dev" \
          -var='security_group_name=["sg-00246283c32b08144"]' \
          -var="instance_type=t2.micro" \
          -var="ami_id=ami-055b20a0020459df7"
