name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Validate & Format'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.0

    - name: 'Terraform Format Check'
      run: terraform fmt -check -recursive

    - name: 'Terraform Validate'
      run: terraform validate
