name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-format:
    name: Check Terraform Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-2"
      run: terraform init

    - name: Terraform format
      run: terraform fmt .
    
    - name: Terraform validate
      run: terraform validate .

    - name: Terraform plan
      run: terraform plan
    
    - name: Terraform apply
      run: terraform apply -var "ami_id=${{ secrets.AMI_ID }}" -var "aws_region=${{ secrets.AWS_REGION }}" -var "instance_type=${{ secrets.INSTANCE_TYPE }}" -var "env=${{ secrets.ENV }}" -var "availability_zones=${{ secrets.AVAILABILITY_ZONES }}" -var "vpc_cidr_block=${{ secrets.VPC_CIDR_BLOCK }}" -var "public_subnet_cidrs=${{ secrets.PUBLIC_SUBNET_CIDRS }}" -var "private_subnet_cidrs=${{ secrets.PRIVATE_SUBNET_CIDRS }}"