name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-format:
    name: Check Terraform Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-2"
      run: terraform init

    - name: Terraform format
      run: terraform fmt .
    
    - name: Terraform validate
      run: terraform validate .

    - name: Terraform plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-east-2"
        AWS_DEFAULT_OUTPUT: "json"
      run: |
        terraform plan -out=webapp.tfplan \
        -var 'ami_id=${{ secrets.AMI_ID }}' \
        -var 'aws_region=${{ secrets.AWS_REGION }}' \
        -var 'instance_type=${{ secrets.INSTANCE_TYPE }}' \
        -var 'env=${{ secrets.ENV }}' \
        -var 'availability_zones=["us-east-2a", "us-east-2b", "us-east-2c"]' \
        -var 'vpc_cidr_block=10.0.0.0/16' \
        -var 'public_subnet_cidrs=["10.0.1.0/24","10.0.2.0/24","10.0.3.0/24"]' \
        -var 'private_subnet_cidrs=["10.0.4.0/24","10.0.5.0/24","10.0.6.0/24"]'
    
    - name: Terraform apply
      run: |
        terraform apply webapp.tfplan -auto-approve