name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: Terraform Check 

    steps:
      - name: Print
        run: echo "Hello World"